name: Pipeline Sprint RestAPI

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x Sprint-RestAPI-TP5/gradlew

    - name: Build with Gradle
      working-directory: ./Sprint-RestAPI-TP5
      run: ./gradlew build

    # Passo 2: Upload do Artefato JAR (Requisito 2.4 do TP5)
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Sprint-RestAPI-Artifact
        path: Sprint-RestAPI-TP5/build/libs/*.jar

    # Passo 3: Resumo do Job em Markdown (Requisito 4.2 do TP5)
    - name: Generate Summary
      run: |
        echo "## ✅ Relatório de Automação TP5" >> $GITHUB_STEP_SUMMARY
        echo "* Build realizado com sucesso: $(date)" >> $GITHUB_STEP_SUMMARY
        echo "* Artefatos gerados e armazenados." >> $GITHUB_STEP_SUMMARY

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: Production # Isso ativa a aprovação manual se configurado no GitHub
    steps:
      - name: Deploy Simulation
        run: echo "Realizando deploy em ambiente de produção após aprovação..."